### ISSUE TITLE
Extend experiment description

### ISSUE THREAD

**Issue by Lotterleben** [Lotterleben/AODVv2-Draft#11]
While at least Jiazi has commented he thinks our new experiment description, imo there are some additional things that could/should be added:

- [ ] Reference past experiments (if any), and what we've learned from them (closely tied to  https://github.com/Lotterleben/AODVv2-Draft/issues/8)
- [ ] Mention desire for new implementations (and interop tests?!) in experiment goals (closely tied to https://github.com/Lotterleben/AODVv2-Draft/issues/9)

What do you think?

**Comment by charliep51** [comment]
Hello folks,

The demand does exist.  AODV is no longer a new toy as it was 15 years 
ago, and that has reduced some of the impetus for making new 
implementations.  Most protocol experts will see that there's not much 
"new" to be expected from AODVv2 compared to AODV.

On the other hand, AODV continues to be used as the design inspiration 
for new reactive protocol designs.  AODVv2 will provide slightly better 
inspiration since it handles unidirectional links better and has a few 
minor optimizations compared to AODV, but perhaps worse performance due 
to RFC 5444.

Anyway I doubt that we could *ever* convince the RFC 5444 crew that 
anything about AODVv2 is good, so there's not much point in trying.

Regards,
Charlie P.

**Comment by Lotterleben** [comment]
If we're going back on standards track we don't need this anymore :)
