### ISSUE TITLE
AODVv2_INTERFACES description

### ISSUE THREAD

**Issue by Lotterleben** [Lotterleben/AODVv2-Draft#2]
it's missing, and Table 4 in `11.3.  Local Settings` is outdated: the Description is not in section 3

**Comment by charliep51** [comment]
Hello Lotte,

Wouldn't it be better to call it the AODVv2InterfaceSet?

Also, how best can I see the revised text for the new definition?

Regards,
Charlie P.

PS. I wanted to follow up on the comments ASAP.  Tomorrow I will try to 
port Pandoc and learn more about github so that I don't have to ask 
these questions.

**Comment by Lotterleben** [comment]
Hi Charlie, I'm not opposed to renaming it if it's important to you. You can look at the revised wording either by searching through https://github.com/Lotterleben/AODVv2-Draft/blob/master/AODVv2-pandoc-edits/AODVv2.mkd or the commits that introduced the main changes: https://github.com/Lotterleben/AODVv2-Draft/commit/d6f86f7e9bba0c1ea409bc284350f85020832c93 and https://github.com/Lotterleben/AODVv2-Draft/commit/38876d60bf5a57254778d4959454d735d37453ce
