### ISSUE TITLE
Local route Set: vague wording.

### ISSUE THREAD

**Issue by Lotterleben** [Lotterleben/AODVv2-Draft#6]
[Jiazi]

> > Alternatively, implementations
> >    MAY choose to modify the Routing Information Base directly.
> 
> This should be either more precise (in which condition, how we can modify
> the RIB?), or be removed.

[Lotte]

> Isn’t the how really implementation specific?

[Jiazi]
My point is that, the sentence is content-free, and we MAY do anything we
want to the RIB, which is not good.

**Comment by charliep51** [comment]
Hello folks,

The proposed resolution and closing the issue is O.K. with me.  I would 
be O.K. with removing all the verbiage about RIB versus FIB anyway, 
because it really is implementation specific and does not affect 
interoperability.  Those terms were added at the request of Jiazi's crew 
in the first place, if I remember correctly. However, since we have 
added them, at this point maybe the best thing is simply to make the 
least modifications to respond to the recent comments.

Regards,
Charlie P.
